# https://docs.astral.sh/ruff/configuration/

line-length = 120
target-version = "py312"

[lint]
select = ["ALL"]
ignore = [
    "FIX",
    "TD", # disable todo warnings
    "ERA",  # allow commented out code
    "ANN002", # missing args type annotation
    "ANN003", # missing kwargs type annotation
    "ANN401", # allow any
    "B006",
    "B008",
    "COM812", # trailing comma
    "C90", # https://docs.astral.sh/ruff/rules/#mccabe-c90
    "D",  # disable docstring warnings
    "EM101",
    "EM102",
    "FBT001",
    "FBT002",
    "PLR09",
    "PLR2004", # magic
    "RET504",
    "RET505",
    "RET508",
    "S101", # allow assert
    "S104",
    "S603", # subprocess untrusted input
    "SIM102",
    "T201", # print
    "TRY003",
    "TRY300",
    "TRY301",
    "W505",
    "ISC001", # recommended to disable for formatting
    "INP001",
    "PT018",
    "G004", # logging f string
    "E501", # line-too-long
    "PLC0415"
]

[lint.isort]
force-sort-within-sections = true

# https://docs.astral.sh/ruff/settings/#per-file-ignores
[lint.per-file-ignores]
"src/speaches/types/**.py" = ["PYI051"]

[format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"
# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false
# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"
